[tools]
"asdf:mise-plugins/mise-nim" = "latest"
"asdf:mise-plugins/mise-v" = "latest"
bun = "latest"
deno = "latest"
pnpm = "latest"
zig = "latest"

[settings]
idiomatic_version_file_enable_tools = []
